name: Master

on:
  push:
    branches:
      - master

jobs:
  master_build:
    name: Master Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
